In [1]:
import pandas as pd
import spark
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:postgres@localhost:5432/taxidb"
)

In [6]:
import pandas as pd

query = "SELECT COUNT(*) AS number_trips FROM trips;"
number_trips = pd.read_sql(query, engine)
number_trips

   number_trips
0       2815614

In [8]:
query2 = ("SELECT DATE(pickup_datetime) AS day,"
          "COUNT(*) AS nb_trips FROM trips "
          "GROUP BY day "
          "ORDER BY day;")

nb_trips_per_day = pd.read_sql(query2, engine)
nb_trips_per_day

           day  nb_trips
0   2024-12-31        21
1   2025-01-01     70353
2   2025-01-02     77542
3   2025-01-03     83756
4   2025-01-04     89264
5   2025-01-05     72211
6   2025-01-06     72852
7   2025-01-07     88599
8   2025-01-08     95886
9   2025-01-09     99956
10  2025-01-10     94130
11  2025-01-11     99342
12  2025-01-12     81063
13  2025-01-13     84903
14  2025-01-14     99977
15  2025-01-15    102707
16  2025-01-16    109721
17  2025-01-17     95748
18  2025-01-18     92357
19  2025-01-19     77510
20  2025-01-20     65746
21  2025-01-21     91757
22  2025-01-22     98792
23  2025-01-23    106224
24  2025-01-24    101684
25  2025-01-25    105552
26  2025-01-26     79405
27  2025-01-27     79663
28  2025-01-28     94249
29  2025-01-29     99384
30  2025-01-30    106167
31  2025-01-31     99092
32  2025-02-01         1

In [9]:
query3 = ("SELECT AVG(total_amount) AS avg_price, "
          "AVG(trip_distance) AS avg_distance "
          "FROM trips;")

average_query = pd.read_sql(query3, engine)
average_query

   avg_price  avg_distance
0  27.688755      3.231127

In [12]:
query4 = ("SELECT l.zone_name, COUNT(*) AS nb_trips "
          "FROM trips t "
          "JOIN location_table l ON t.pickup_location_id = l.pulocation_id "
          "GROUP BY l.zone_name "
          "ORDER BY nb_trips DESC "
          "LIMIT 10;")

trips_location_query = pd.read_sql(query4, engine)
trips_location_query

                      zone_name  nb_trips
0         Upper East Side South    148003
1                Midtown Center    146750
2         Upper East Side North    137810
3                   JFK Airport    133722
4  Penn Station/Madison Sq West    108175
5     Times Sq/Theatre District    107524
6                  Midtown East    105056
7           Lincoln Square East     97557
8             LaGuardia Airport     85429
9                 Midtown North     84648

In [14]:
query5 = ("SELECT p.payment_name, COUNT(*) AS nb_trips "
          "FROM trips t "
          "JOIN payment p ON t.payment_type_id = p.payment_type_id "
          "GROUP BY p.payment_name;")

payments_details_query = pd.read_sql(query5, engine)
payments_details_query

  payment_name  nb_trips
0         Cash    364129
1  Credit card   2404258
2      Dispute     35469
3    No charge     11758

In [18]:
query6 = ("SELECT EXTRACT(HOUR FROM pickup_datetime) AS hour, COUNT(*) AS trips "
          "FROM trips "
          "GROUP BY hour "
          "ORDER BY trips DESC;")

rush_hours_query= pd.read_sql(query6, engine)
rush_hours_query

    hour   trips
0   17.0  206873
1   18.0  205869
2   16.0  190657
3   15.0  188113
4   14.0  178738
5   19.0  174562
6   13.0  165886
7   21.0  161460
8   20.0  157845
9   12.0  157037
10  11.0  144590
11  22.0  134099
12  10.0  133545
13   9.0  122168
14   8.0  105792
15  23.0   94311
16   7.0   74110
17   0.0   65111
18   1.0   43674
19   6.0   34869
20   2.0   29452
21   3.0   19147
22   5.0   15376
23   4.0   12330

In [19]:
query7 = ("SELECT DATE(pickup_datetime) AS day, SUM(total_amount) AS revenue "
          "FROM trips "
          "GROUP BY day "
          "ORDER BY day;")

daily_revenue_query= pd.read_sql(query7, engine)
daily_revenue_query

           day     revenue
0   2024-12-31      589.17
1   2025-01-01  2079810.80
2   2025-01-02  2303635.80
3   2025-01-03  2356609.00
4   2025-01-04  2393907.80
5   2025-01-05  2131352.80
6   2025-01-06  2109628.00
7   2025-01-07  2405528.80
8   2025-01-08  2553480.00
9   2025-01-09  2727049.00
10  2025-01-10  2598747.20
11  2025-01-11  2538029.20
12  2025-01-12  2276602.50
13  2025-01-13  2375751.50
14  2025-01-14  2711628.20
15  2025-01-15  2793077.50
16  2025-01-16  3033697.80
17  2025-01-17  2674660.00
18  2025-01-18  2341992.50
19  2025-01-19  1970777.00
20  2025-01-20  2864735.00
21  2025-01-21  2527626.00
22  2025-01-22  2636950.50
23  2025-01-23  2885775.50
24  2025-01-24  2752994.00
25  2025-01-25  2624521.20
26  2025-01-26  2208035.20
27  2025-01-27  2240444.50
28  2025-01-28  2530684.00
29  2025-01-29  2690986.50
30  2025-01-30  2924306.50
31  2025-01-31  2698815.20
32  2025-02-01       22.13

In [21]:
query8 = ("SELECT AVG(CASE WHEN trip_distance > 0 THEN total_amount / trip_distance END) AS avg_price_per_mile "
          "FROM trips;")

avg_price_per_mile_query= pd.read_sql(query8, engine)
avg_price_per_mile_query

   avg_price_per_mile
0           18.590486

In [22]:
query9 = ("SELECT SUM(CASE WHEN trip_distance = 0 THEN 1 ELSE 0 END) AS zero_distance, "
          "SUM(CASE WHEN total_amount = 0 THEN 1 ELSE 0 END) AS zero_total, "
          "SUM(CASE WHEN dropoff_datetime < pickup_datetime THEN 1 ELSE 0 END) AS negative_duration "
          "FROM trips;")

trips_check_query= pd.read_sql(query9, engine)
trips_check_query

   zero_distance  zero_total  negative_duration
0              0           0                  0

In [27]:
query10 = ("SELECT l.zone_name, COUNT(*) trips FROM trips t "
          "JOIN location_table l ON t.pickup_location_id = l.pulocation_id "
          "GROUP BY l.zone_name "
          "ORDER BY trips DESC "
          "LIMIT 10;")

top_10_zones_pickup_query= pd.read_sql(query10, engine)
top_10_zones_pickup_query

                      zone_name   trips
0         Upper East Side South  148003
1                Midtown Center  146750
2         Upper East Side North  137810
3                   JFK Airport  133722
4  Penn Station/Madison Sq West  108175
5     Times Sq/Theatre District  107524
6                  Midtown East  105056
7           Lincoln Square East   97557
8             LaGuardia Airport   85429
9                 Midtown North   84648

In [28]:
query11 = ("SELECT l.zone_name, COUNT(*) trips FROM trips t "
           "JOIN location_table l ON t.dropoff_location_id = l.pulocation_id "
           "GROUP BY l.zone_name "
           "ORDER BY trips DESC "
           "LIMIT 10;")

top_10_zones_dropoff_query= pd.read_sql(query11, engine)
top_10_zones_dropoff_query

                   zone_name   trips
0      Upper East Side North  144476
1      Upper East Side South  133560
2             Midtown Center  111895
3  Times Sq/Theatre District   89103
4        Lincoln Square East   85342
5      Upper West Side South   84955
6                Murray Hill   82651
7            Lenox Hill West   80319
8               Midtown East   79603
9              Midtown North   72780

In [29]:
query12 = ("SELECT lp.zone_name AS pickup_zone, ld.zone_name AS dropoff_zone, COUNT(*) AS trips "
           "FROM trips t JOIN location_table lp ON t.pickup_location_id = lp.pulocation_id "
           "JOIN location_table ld ON t.dropoff_location_id = ld.pulocation_id "
           "GROUP BY pickup_zone, dropoff_zone "
           "ORDER BY trips DESC LIMIT 20;")

top_20_zones_query= pd.read_sql(query12, engine)
top_20_zones_query

                     pickup_zone               dropoff_zone  trips
0          Upper East Side South      Upper East Side North  23437
1          Upper East Side North      Upper East Side South  20241
2          Upper East Side North      Upper East Side North  16384
3          Upper East Side South      Upper East Side South  15613
4                 Midtown Center      Upper East Side South  10703
5          Upper East Side South             Midtown Center   9363
6                 Midtown Center      Upper East Side North   9142
7          Upper West Side South      Upper West Side North   8875
8            Lincoln Square East      Upper West Side South   8562
9          Upper West Side South        Lincoln Square East   8052
10               Lenox Hill West      Upper East Side North   7998
11  Penn Station/Madison Sq West  Times Sq/Theatre District   7933
12         Upper East Side North            Lenox Hill West   7437
13         Upper East Side South            Lenox Hill West   7308
14         Upper East Side South               Midtown East   7308
15         Upper East Side North             Midtown Center   7149
16         Upper West Side North      Upper West Side South   7113
17         Upper East Side North      Upper West Side South   6975
18                Yorkville West      Upper East Side North   6806
19  Penn Station/Madison Sq West             Midtown Center   6666