# NYC Taxi – Notebook d’analyse (Exo4 enrichi),

Objectifs :

- Vérifier le chargement (qualité + volumes),
- KPI globaux,
- Tendances temporelles (jour / heure / weekday),
- Comparatifs par **mois** (YYYY-MM),
- Analyses business : paiements, vendors, zones, boroughs,
- Préparer des requêtes réutilisables pour l'interface Streamlit (ou même un dashboard PowerBI),

⚠ Dataset très gros (~20M lignes) → on travaille **toujours en agrégé** et **filtré**.

In [27]:
# ====== Imports & connexion DB ======

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
from sqlalchemy import create_engine, text
pio.renderers.default = "browser"

# Adaptez si besoin
DB_URL = "postgresql://postgres:postgres@localhost:5432/taxidb"
engine = create_engine(DB_URL, pool_pre_ping=True)

def q(sql: str, params=None) -> pd.DataFrame:
    #Helper: exécute une requête SQL et renvoie un DataFrame Pandas.
    return pd.read_sql(text(sql), engine, params=params or {})

print("OK: engine created")

OK: engine created

## 1) Paramètres d'analyse

On choisit un ou plusieurs mois `YYYY-MM` pour faire des comparatifs.

In [5]:
# Liste des mois présents
months_df = q("SELECT DISTINCT month FROM trips WHERE month IS NOT NULL ORDER BY month")
months = months_df["month"].tolist()
months

['2007-12',
 '2009-01',
 '2024-12',
 '2025-01',
 '2025-02',
 '2025-03',
 '2025-04',
 '2025-05',
 '2025-06']

In [6]:
# Choix par défaut : tous les mois
# Vous pouvez mettre par ex: selected_months = ["2025-01","2025-02"]
selected_months = months

print("Selected months:", selected_months)

Selected months: ['2007-12', '2009-01', '2024-12', '2025-01', '2025-02', '2025-03', '2025-04', '2025-05', '2025-06']

 ## 2) Contrôle qualité rapide (sanity checks)

But : s'assurer que le nettoyage a bien été appliqué

In [8]:
checks = q("SELECT"
"  COUNT(*) AS total_rows,"
"  SUM(CASE WHEN trip_distance <= 0 THEN 1 ELSE 0 END) AS bad_distance,"
"  SUM(CASE WHEN total_amount <= 0 THEN 1 ELSE 0 END) AS bad_total,"
"  SUM(CASE WHEN fare_amount <= 0 THEN 1 ELSE 0 END) AS bad_fare,"
"  SUM(CASE WHEN passenger_count <= 0 OR passenger_count > 9 THEN 1 ELSE 0 END) AS bad_passengers,"
"  SUM(CASE WHEN dropoff_datetime < pickup_datetime THEN 1 ELSE 0 END) AS bad_duration "
           "FROM trips;")

checks

   total_rows  bad_distance  bad_total  bad_fare  bad_passengers  bad_duration
0    20528933             0          0         0               0           541

## 3) KPI globaux

- Nb courses
- Revenu total
- Prix moyen
- Distance moyenne
- Tip rate (% courses avec tip)
- Prix par mile moyen

In [10]:
kpi = q("SELECT"
"  COUNT(*) AS trips,"
"  SUM(total_amount) AS revenue,"
"  AVG(total_amount) AS avg_total,"
"  AVG(trip_distance) AS avg_distance,"
"  AVG(CASE WHEN trip_distance > 0 THEN total_amount / trip_distance END) AS avg_price_per_mile,"
"  100.0 * AVG(CASE WHEN tip_amount > 0 THEN 1 ELSE 0 END) AS tip_rate_pct "
"FROM trips;")
kpi

,trips,revenue,avg_total,avg_distance,avg_price_per_mile,tip_rate_pct
0,20528933,588039170.0,28.6938,3.533818,19.369594,80.600239

## 4) Comparatif par mois (l'analyse la pluse importante pour les visualisations)

On produit une table mensuelle : volumes, revenus, prix moyen, distance, tip rate.

In [13]:
monthly = q("SELECT"
"  month,"
"  COUNT(*) AS trips,"
"  SUM(total_amount) AS revenue,"
"  AVG(total_amount) AS avg_total,"
"  AVG(trip_distance) AS avg_distance,"
"  100.0 * AVG(CASE WHEN tip_amount > 0 THEN 1 ELSE 0 END) AS tip_rate_pct "
"FROM trips "
"WHERE month IS NOT NULL "
"GROUP BY month "
"ORDER BY month;")

monthly.head()

     month    trips       revenue  avg_total  avg_distance  tip_rate_pct
0  2007-12        1  2.275000e+01  22.750000      3.000000      0.000000
1  2009-01        2  1.031200e+02  51.559999      7.620000     50.000000
2  2024-12       42  1.178340e+03  28.055714      3.657619     71.428571
3  2025-01  5631214  1.559397e+08  27.688761      3.231128     80.546486
4  2025-02  2656832  7.270386e+07  27.364191      3.118537     81.289709

In [28]:
# Volume & revenu
fig = px.line(
    monthly,
    x="month",
    y=["trips", "revenue"],
    markers=True,
    title="Evolution mensuelle – Volume & Revenu"
)
fig.show()

# Qualité moyenne
fig = px.line(
    monthly,
    x="month",
    y=["avg_total", "avg_distance", "tip_rate_pct"],
    markers=True,
    title="Evolution mensuelle – Prix, distance, tips"
)
fig.show()
"""Une notifaction de votre navigateur par défaut s'affichera, veuillez cliquer dessus pour afficher les figures"""

## 5) Analyse temporelle fine

### 5.1 Courses par jour (sur les mois sélectionnés)

(⚠ Si on prend tous les mois, ça reste OK car c’est agrégé).

In [31]:
daily = q("""
SELECT
DATE(pickup_datetime) AS day, month,
COUNT(*) AS trips,
SUM(total_amount) AS revenue
FROM trips
WHERE month = ANY(:months)
GROUP BY day, month
ORDER BY day""", {"months": selected_months})


daily.head()

          day    month   trips       revenue
0  2007-12-05  2007-12       1  2.275000e+01
1  2009-01-01  2009-01       2  1.031200e+02
2  2024-12-31  2024-12      42  1.178340e+03
3  2025-01-01  2025-01  140706  4.159761e+06
4  2025-01-02  2025-01  155084  4.607266e+06

In [34]:
fig = px.line(daily, x="day", y="trips", color="month", markers=False, title="Courses par jour (comparatif par mois)")
fig.show()

### 5.2 Heures de pointe (distribution par heure)

In [32]:
hourly = q("""
SELECT
EXTRACT(HOUR FROM pickup_datetime) AS hour, month,
COUNT(*) AS trips,
AVG(total_amount) AS avg_total
FROM trips
WHERE month = ANY(:months)
GROUP BY hour, month
ORDER BY hour""", {"months": selected_months})

hourly.head()

   hour    month   trips  avg_total
0   0.0  2009-01       2  51.559999
1   0.0  2025-01  130220  28.975440
2   0.0  2025-02   63976  28.344101
3   0.0  2025-03   85012  29.838588
4   0.0  2025-04   72480  29.181729

In [33]:
fig = px.line(hourly, x="hour", y="trips", color="month", markers=True, title="Distribution des courses par heure")
fig.show()

### 5.3 Jour de semaine (weekday)

Postgres: 'EXTRACT(DOW ...)' : 0=Dimanche ... 6=Samedi.

In [35]:
weekday = q("""
SELECT
    EXTRACT(DOW FROM pickup_datetime) AS dow, month,
    COUNT(*) AS trips,
    AVG(total_amount) AS avg_total
FROM trips
WHERE month = ANY(:months)
GROUP BY dow, month
ORDER BY dow;""", {"months": selected_months})

weekday

    dow    month   trips  avg_total
0   0.0  2025-01  620378  27.681927
1   0.0  2025-02  314634  27.659078
2   0.0  2025-03  424419  29.534196
3   0.0  2025-04  340525  29.516945
4   0.0  2025-05  343872  30.994494
5   0.0  2025-06  405048  31.537177
6   1.0  2025-01  606328  31.634292
7   1.0  2025-02  318010  28.797291
8   1.0  2025-03  433967  30.146411
9   1.0  2025-04  352967  30.194858
10  1.0  2025-05  353300  31.783280
11  1.0  2025-06  447051  30.730954
12  2.0  2024-12      42  28.055714
13  2.0  2025-01  749164  27.164462
14  2.0  2025-02  382071  27.438395
15  2.0  2025-03  392470  28.534109
16  2.0  2025-04  511551  29.081925
17  2.0  2025-05  420794  30.316829
18  2.0  2025-06  412273  29.618394
19  3.0  2007-12       1  22.750000
20  3.0  2025-01  934244  27.303346
21  3.0  2025-02  401243  27.412780
22  3.0  2025-03  422777  28.350697
23  3.0  2025-04  549309  28.892033
24  3.0  2025-05  449327  30.515937
25  3.0  2025-06  441725  30.407310
26  4.0  2009-01       2  51.559999
27  4.0  2025-01  999220  27.769901
28  4.0  2025-02  422313  27.622356
29  4.0  2025-03  450771  28.819147
30  4.0  2025-04  451163  29.441387
31  4.0  2025-05  581463  30.719742
32  4.0  2025-06  439480  30.183138
33  5.0  2025-01  948850  27.574350
34  5.0  2025-02  417125  27.926210
35  5.0  2025-03  417624  28.598020
36  5.0  2025-04  426833  28.603849
37  5.0  2025-05  532590  30.244299
38  5.0  2025-06  393374  30.246314
39  6.0  2025-01  773030  25.609015
40  6.0  2025-02  401436  25.023030
41  6.0  2025-03  537479  26.228352
42  6.0  2025-04  425951  26.505703
43  6.0  2025-05  510728  27.783517
44  6.0  2025-06  372011  28.285206

In [36]:
dow_names = {0:"Sun",1:"Mon",2:"Tue",3:"Wed",4:"Thu",5:"Fri",6:"Sat"}
weekday["dow_name"] = weekday["dow"].map(dow_names)
fig = px.bar(weekday, x="dow_name", y="trips", color="month", barmode="group", title="Courses par jour de semaine")
fig.show()

## 6) Vendors & Paiements

Deux analyses très attendues dans une soutenance :
- Part de marché par vendor
- Répartition des modes de paiement (et comparaison par mois)

In [41]:
vendor_share = q("""
SELECT
    t.month, v.vendor_name, COUNT(*) AS trips FROM trips t
    JOIN vendor v ON t.vendor_id = v.vendor_id
    WHERE t.month = ANY(:months)
    GROUP BY t.month, v.vendor_name
    ORDER BY t.month, trips DESC;""", {"months": selected_months})

vendor_share.head()

     month                        vendor_name    trips
0  2007-12                 Curb Mobility, LLC        1
1  2009-01                 Curb Mobility, LLC        2
2  2024-12                 Curb Mobility, LLC       42
3  2025-01                 Curb Mobility, LLC  4374134
4  2025-01  Creative Mobile Technologies, LLC  1257080

In [42]:
fig = px.bar(vendor_share, x="vendor_name", y="trips", color="month", barmode="group",title="Parts de marché Vendor (comparatif par mois)")

fig.show()

In [44]:
pay = q("""
SELECT
  t.month,
  p.payment_name,
  COUNT(*) AS trips
FROM trips t
JOIN payment p ON t.payment_type_id = p.payment_type_id
WHERE t.month = ANY(:months)
GROUP BY t.month, p.payment_name
ORDER BY t.month, trips DESC;
""", {"months": selected_months})

pay.head()

     month payment_name  trips
0  2007-12         Cash      1
1  2009-01         Cash      1
2  2009-01  Credit card      1
3  2024-12  Credit card     30
4  2024-12         Cash     12

In [45]:
fig = px.bar(pay, x="payment_name", y="trips", color="month", barmode="group",title="Répartition paiements (comparatif par mois)")
fig.show()

## 7) Zones & Boroughs (pickups / dropoffs)

On veut :
- Top zones pickup/dropoff
- Comparatif par mois
- Boroughs les plus actifs

In [46]:
top_pickup = q("""
SELECT
  t.month,
  b.borough_name,
  l.zone_name,
  COUNT(*) AS trips
FROM trips t
JOIN location_table l ON t.pickup_location_id = l.pulocation_id
JOIN borough b ON l.borough_id = b.borough_id
WHERE t.month = ANY(:months)
GROUP BY t.month, b.borough_name, l.zone_name
ORDER BY trips DESC
LIMIT 20;
""", {"months": selected_months})

top_pickup

fig = px.bar(top_pickup, x="trips", y="zone_name", color="borough_name", facet_col="month",
             orientation="h", title="Top 20 zones PICKUP (sur mois sélectionnés)")
fig.update_layout(height=600)
fig.show()

In [48]:
borough_activity = q("""
SELECT
  t.month,
  b.borough_name,
  COUNT(*) AS trips,
  SUM(t.total_amount) AS revenue,
  AVG(t.total_amount) AS avg_total
FROM trips t
JOIN location_table l ON t.pickup_location_id = l.pulocation_id
JOIN borough b ON l.borough_id = b.borough_id
WHERE t.month = ANY(:months)
GROUP BY t.month, b.borough_name
ORDER BY t.month, trips DESC;
""", {"months": selected_months})

borough_activity.head()

fig = px.bar(borough_activity, x="borough_name", y="trips", color="month", barmode="group",
             title="Activité par Borough (PICKUP) – comparatif par mois")
fig.show()

## 8) Analyse prix: tips, surcharges, outliers raisonnables

- Tip rate et tip moyen par mois
- Congestion surcharge / airport fee
- Détection rapide d’anomalies

In [49]:
tips_month = q("""
SELECT
  month,
  100.0 * AVG(CASE WHEN tip_amount > 0 THEN 1 ELSE 0 END) AS tip_rate_pct,
  AVG(tip_amount) AS avg_tip,
  AVG(CASE WHEN total_amount > 0 THEN tip_amount / total_amount END) AS avg_tip_ratio
FROM trips
WHERE month = ANY(:months)
GROUP BY month
ORDER BY month;
""", {"months": selected_months})

tips_month

fig = px.line(tips_month, x="month", y=["tip_rate_pct","avg_tip","avg_tip_ratio"], markers=True,
              title="Tips – comparatif mensuel")
fig.show()

In [50]:
surcharges = q("""
SELECT
  month,
  AVG(congestion_surcharge) AS avg_congestion,
  AVG(airport_fee) AS avg_airport_fee,
  AVG(tolls_amount) AS avg_tolls
FROM trips
WHERE month = ANY(:months)
GROUP BY month
ORDER BY month;
""", {"months": selected_months})

surcharges

fig = px.line(surcharges, x="month", y=["avg_congestion","avg_airport_fee","avg_tolls"], markers=True,
             title="Surcharges – comparatif mensuel")
fig.show()

## 9) Requêtes "dashboard-ready"

Ces requêtes sont parfaites pour Streamlit / PowerBI :
- agrégées
- filtrables par `month`
- rapides sur gros volume (~20M lignes)

On crée aussi des index pour accélérer les dashboards.

### Recommandation performance (SQL)

À exécuter **une seule fois** dans PostgreSQL :
- 'CREATE INDEX IF NOT EXISTS idx_trips_month ON trips(month);'
- 'CREATE INDEX IF NOT EXISTS idx_trips_pickup_datetime ON trips(pickup_datetime);'
- 'CREATE INDEX IF NOT EXISTS idx_trips_pickup_loc ON trips(pickup_location_id);'

In [56]:
# --- KPI mensuels (cartes KPI) ---
kpi_month = q("""
              SELECT
                  month,
                  COUNT(*) AS trips,
                  SUM(total_amount) AS revenue,
                  AVG(total_amount) AS avg_total,
                  AVG(trip_distance) AS avg_distance,
                  100.0 * AVG(CASE WHEN tip_amount > 0 THEN 1 ELSE 0 END) AS tip_rate_pct
              FROM trips
              WHERE month IS NOT NULL
              GROUP BY month
              ORDER BY month;
              """)

kpi_month

     month    trips       revenue  avg_total  avg_distance  tip_rate_pct
0  2007-12        1  2.275000e+01  22.750000      3.000000      0.000000
1  2009-01        2  1.031200e+02  51.559999      7.620000     50.000000
2  2024-12       42  1.178340e+03  28.055714      3.657619     71.428571
3  2025-01  5631214  1.559355e+08  27.688761      3.231128     80.546486
4  2025-02  2656832  7.270448e+07  27.364191      3.118537     81.289709
5  2025-03  3079507  8.783470e+07  28.521926      3.401207     80.698209
6  2025-04  3058299  8.824064e+07  28.852198      4.025996     80.370624
7  2025-05  3192074  9.651930e+07  30.236132      4.077381     80.672785
8  2025-06  2910962  8.784264e+07  30.175699      3.525536     80.133166

In [57]:
vendor_dashboard = q("""
                     SELECT
                         t.month,
                         v.vendor_name,
                         COUNT(*) AS trips
                     FROM trips t
                              JOIN vendor v ON t.vendor_id = v.vendor_id
                     WHERE t.month IS NOT NULL
                     GROUP BY t.month, v.vendor_name
                     ORDER BY t.month, trips DESC;
                     """)

vendor_dashboard

      month                        vendor_name    trips
0   2007-12                 Curb Mobility, LLC        1
1   2009-01                 Curb Mobility, LLC        2
2   2024-12                 Curb Mobility, LLC       42
3   2025-01                 Curb Mobility, LLC  4374134
4   2025-01  Creative Mobile Technologies, LLC  1257080
5   2025-02                 Curb Mobility, LLC  2046211
6   2025-02  Creative Mobile Technologies, LLC   610621
7   2025-03                 Curb Mobility, LLC  2412425
8   2025-03  Creative Mobile Technologies, LLC   667082
9   2025-04                 Curb Mobility, LLC  2410304
10  2025-04  Creative Mobile Technologies, LLC   647995
11  2025-05                 Curb Mobility, LLC  2501257
12  2025-05  Creative Mobile Technologies, LLC   690817
13  2025-06                 Curb Mobility, LLC  2279502
14  2025-06  Creative Mobile Technologies, LLC   631460

In [58]:
payment_dashboard = q("""
                      SELECT
                          t.month,
                          p.payment_name,
                          COUNT(*) AS trips
                      FROM trips t
                               JOIN payment p ON t.payment_type_id = p.payment_type_id
                      WHERE t.month IS NOT NULL
                      GROUP BY t.month, p.payment_name
                      ORDER BY t.month, trips DESC;
                      """)

payment_dashboard

      month payment_name    trips
0   2007-12         Cash        1
1   2009-01         Cash        1
2   2009-01  Credit card        1
3   2024-12  Credit card       30
4   2024-12         Cash       12
5   2025-01  Credit card  4808511
6   2025-01         Cash   728249
7   2025-01      Dispute    70938
8   2025-01    No charge    23516
9   2025-02  Credit card  2295658
10  2025-02         Cash   315049
11  2025-02      Dispute    35009
12  2025-02    No charge    11116
13  2025-03  Credit card  2646406
14  2025-03         Cash   374559
15  2025-03      Dispute    44680
16  2025-03    No charge    13862
17  2025-04  Credit card  2617217
18  2025-04         Cash   379317
19  2025-04      Dispute    47515
20  2025-04    No charge    14250
21  2025-05  Credit card  2746106
22  2025-05         Cash   380012
23  2025-05      Dispute    51136
24  2025-05    No charge    14820
25  2025-06  Credit card  2499687
26  2025-06         Cash   348873
27  2025-06      Dispute    48549
28  2025-06    No charge    13852
29  2025-06      Unknown        1

In [59]:
pickup_zones_dashboard = q("""
                           SELECT
                               t.month,
                               b.borough_name,
                               l.zone_name,
                               COUNT(*) AS trips
                           FROM trips t
                                    JOIN location_table l ON t.pickup_location_id = l.pulocation_id
                                    JOIN borough b ON l.borough_id = b.borough_id
                           WHERE t.month IS NOT NULL
                           GROUP BY t.month, b.borough_name, l.zone_name
                           ORDER BY trips DESC
                               LIMIT 50;
                           """)

pickup_zones_dashboard

      month borough_name                     zone_name   trips
0   2025-01    Manhattan         Upper East Side South  296007
1   2025-01    Manhattan                Midtown Center  293500
2   2025-01    Manhattan         Upper East Side North  275620
3   2025-01       Queens                   JFK Airport  267443
4   2025-01    Manhattan  Penn Station/Madison Sq West  216349
5   2025-01    Manhattan     Times Sq/Theatre District  215048
6   2025-01    Manhattan                  Midtown East  210112
7   2025-01    Manhattan           Lincoln Square East  195112
8   2025-05       Queens                   JFK Airport  175803
9   2025-05    Manhattan         Upper East Side South  175061
10  2025-01       Queens             LaGuardia Airport  170856
11  2025-06       Queens                   JFK Airport  169664
12  2025-01    Manhattan                 Midtown North  169294
13  2025-04    Manhattan         Upper East Side South  166278
14  2025-01    Manhattan         Upper West Side South  163652
15  2025-04    Manhattan                Midtown Center  161325
16  2025-01    Manhattan                   Murray Hill  158992
17  2025-01    Manhattan                      Union Sq  156007
18  2025-03    Manhattan                Midtown Center  155349
19  2025-05    Manhattan                Midtown Center  154283
20  2025-01    Manhattan                  East Chelsea  150546
21  2025-03    Manhattan         Upper East Side South  150474
22  2025-06    Manhattan         Upper East Side South  150307
23  2025-05    Manhattan         Upper East Side North  147964
24  2025-03       Queens                   JFK Airport  146842
25  2025-04       Queens                   JFK Airport  144241
26  2025-06    Manhattan                Midtown Center  143601
27  2025-04    Manhattan         Upper East Side North  140611
28  2025-01    Manhattan                  Clinton East  140423
29  2025-01    Manhattan               Lenox Hill West  139964
30  2025-02    Manhattan         Upper East Side South  138211
31  2025-02    Manhattan                Midtown Center  135974
32  2025-03    Manhattan         Upper East Side North  130724
33  2025-01    Manhattan               Lenox Hill East  126619
34  2025-02    Manhattan         Upper East Side North  125448
35  2025-06    Manhattan         Upper East Side North  124468
36  2025-01    Manhattan                 Midtown South  122610
37  2025-01    Manhattan                  East Village  119293
38  2025-01    Manhattan                  West Village  119126
39  2025-05       Queens             LaGuardia Airport  118789
40  2025-03    Manhattan  Penn Station/Madison Sq West  117899
41  2025-04    Manhattan     Times Sq/Theatre District  114717
42  2025-03    Manhattan     Times Sq/Theatre District  114457
43  2025-01    Manhattan         Upper West Side North  114206
44  2025-02       Queens                   JFK Airport  114201
45  2025-04    Manhattan  Penn Station/Madison Sq West  113751
46  2025-03    Manhattan                  Midtown East  112807
47  2025-05    Manhattan                  Midtown East  112765
48  2025-01    Manhattan                Yorkville West  112100
49  2025-04    Manhattan                  Midtown East  111760

In [60]:
hourly_dashboard = q("""
                     SELECT
                         month,
                         EXTRACT(HOUR FROM pickup_datetime) AS hour,
                         COUNT(*) AS trips
                     FROM trips
                     WHERE month IS NOT NULL
                     GROUP BY month, hour
                     ORDER BY month, hour;
                     """)

hourly_dashboard

       month  hour   trips
0    2007-12  18.0       1
1    2009-01   0.0       2
2    2024-12  20.0       6
3    2024-12  21.0       6
4    2024-12  23.0      30
..       ...   ...     ...
144  2025-06  19.0  184298
145  2025-06  20.0  165744
146  2025-06  21.0  170356
147  2025-06  22.0  150745
148  2025-06  23.0  111515

[149 rows x 3 columns]